// SET GENERAL ACCOUNT INFO
export const SET_GENERAL_ACCOUNT_INFO = 'SET_GENERAL_ACCOUNT_INFO';

// SET DISPLAY
export const SET_COLOR_MODE = 'SET_COLOR_MODE';

// REQUEST LOGIN
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const LOGOUT = "LOGOUT";
